# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: aulaMaven
#vai ser ativando quando
on:
  push:
    branches:  main 
    
  pull_request:
    branches:  main 

jobs:
  build:
  
    runs-on: ubuntu-latest
    #para que o comando funcione precisamos estar na pasta principal do app, ou seja, a pasta demo
    defaults:
      run:
         working-directory: demo
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
    
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    #validar as infosse estão preenchidas e validas
    - name: verify info
      run: mvn validate
      
    #o codigo está compilando
    - name: compile code
      run: mvn compile
      
    # Testa todos os testes unitarios
    - name: testing unitary test
      run: mvn test
    #instala as depedencias
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
#------------------
  verify:
    runs-on: ubuntu-latest
    environment:
      name: verify
      url: 'gabriel-masson.com'
    needs: build #coloca uma dependencia no primeiro job

    defaults:
      run:
         working-directory: demo
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
    
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven    
    
    #o pacote gerado no estágio anterior é instalado em um ambiente de teste de integração
    - name: Install package in environment integration test
      run: mvn integration-test
    #vamos verificar se o pacote é valido e se atende os padrões de qualidade
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
      
    - name: Install in local repository 
      run: mvn install
