# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: aulaMaven
#vai ser ativando quan
on:
  push:
    branches:  main 
  pull_request:
    branches:  main 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    #instala as depedencias
    - name: Build with Maven
      run: mvn -B package 
    #vamos verificar se o pacote é valido e se atende os padrões de qualidade
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
